# Generated by Django 3.2.4 on 2021-10-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_meet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://res.cloudinary.com/chryzhub/image/upload/v1632356842/projects/default_profile_img_ee5jrv.png', null=True, upload_to=''),
        ),
    ]
