# Generated by Django 3.2.4 on 2021-10-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_meet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
