# Generated by Django 3.2.4 on 2021-10-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_meet_app', '0002_auto_20211013_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
