# Generated by Django 3.2.4 on 2021-10-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_meet_app', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='hi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='alabaolanrewaju13@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Olanrewaju', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Alaba', max_length=150),
        ),
    ]
